# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{smtp_tls}
  s.version = "1.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Hodel", "Kyle Maxwell"]
  s.date = %q{2009-10-02}
  s.default_executable = %q{mail_smtp_tls}
  s.description = %q{Provides SMTP STARTTLS support for Ruby 1.8.6 (built-in for 1.8.7+).  Simply
    require 'smtp_tls' and use the Net::SMTP#enable_starttls method to talk to
    servers that use STARTTLS.}
  s.email = %q{drbrain@segment7.net}
  s.executables = ["mail_smtp_tls"]
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    "History.txt",
     "Manifest.txt",
     "README.txt",
     "Rakefile",
     "VERSION",
     "bin/mail_smtp_tls",
     "lib/smtp_tls.rb"
  ]
  s.homepage = %q{http://github.com/seattlerb/smtp_tls}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new("~> 1.8.6.0")
  s.rubygems_version = %q{1.3.3}
  s.summary = %q{Provides SMTP STARTTLS support for Ruby 1.8.6 (built-in for 1.8.7+)}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
